apiVersion: v1
kind: Service
metadata:
  name: webapp
  namespace: student99
  labels:
    app: webapp
spec:
  selector:
    app: webapp
  type: NodePort
  ports:
     - port: 80
       nodePort: 32099
