apiVersion: v1
kind: Service
metadata:
  name: webapp
  labels:
    app: webapp
spec:
  selector:
    app: webapp
    rollout: webapp_old
  type: NodePort
  ports:
     - port: 80
       nodePort: 32000
