# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"
  config.vm.network "forwarded_port", guest: 8080, host: 8080
  config.vm.network "forwarded_port", guest: 8081, host: 8081
  config.vm.network "forwarded_port", guest: 8082, host: 8082

  config.vm.provider "virtualbox" do |vb|
      vb.cpus = 2 
      vb.memory = "2048"
  end
  
  config.vm.provision "shell", inline: <<-SHELL
     apt-get update -y
     apt-get install -y apt-transport-https ca-certificates curl gnupg-agent software-properties-common
     curl -fsSL https://download.docker.com/linux/ubuntu/gpg | sudo apt-key add -
     add-apt-repository "deb [arch=amd64] https://download.docker.com/linux/ubuntu $(lsb_release -cs) stable"
     apt-get update -y
     apt-get install -y docker-ce docker-ce-cli containerd.io
     adduser vagrant docker
  SHELL
end
